executor: parallel

tasks:
  - source: tasks.get.metadata
    product:
      metadata: products/raw/metadata.csv
  
  - source: tasks.get.embeddings
    product: products/raw/embeddings.tar.gz

  - source: tasks.get.extract_embeddings
    product: products/raw/embeddings.csv
  