executor: parallel

tasks:
  - source: tasks.get.metadata
    product:
      metadata: products/raw/metadata.csv
  
  - source: tasks.get.embeddings
    product: products/raw/embeddings.tar.gz

  - source: tasks.get.extract_embeddings
    product: products/raw/embeddings.csv

  - source: scripts/clean.py
    name: clean
    product:
      nb: products/clean/output_cleaning.ipynb
      cleaned_metadata: products/clean/cleaned_metadata.parquet
    params:
      sample: False
      link_journal: True
   
  - source: scripts/retrieval.py
    name: retrieval
    product:
      nb: products/retrieval/output_retrieval.ipynb
      whoosh: products/retrieval/index.tar.gz
  
  - source: scripts/embeddings_feature.py
    name: embeddings_feature
    product:
      nb: products/embeddings/output_embeddings_feature.ipynb
      embeddings_100: products/embeddings/embeddings_100.parquet
      pca_100: products/embeddings/pca_100.joblib
    params:
      sample: False
  
  - source: scripts/similar.py
    name: similar
    product:
      nb: products/similar/output_similar.ipynb
      annoy_idx: products/similar/embeddings.ann
      annoy_metadata: products/similar/annoy_metadata.parquet
  
  - source: scripts/production_metadata.py
    name: production_metadata
    product:
      nb: products/production_metadata/output_production_metadata.ipynb
      metadata: products/production_metadata/metadata.csv

